Blog/ViewModels/PostViewModel.cs
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.ViewModels
{
    public class PostViewModel
    {
        public Post Post { get; set; }
        public SelectList PostStatus { get; set; }
    }
}

Blog/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Blog.Models;
using Blog.Repositories;
using Blog.ViewModels;
using Microsoft.AspNet.Identity;

namespace Blog.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CommentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        // GET: /Comment/
        // Returns comments based on the provided parameters:
        // no parameters: all comments in the database
        // postId: id of the post to list the comments for
        // pending: true, if only comments that have not been approved are to be returned
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int? postId, bool pending = false)
        {
            if (postId == null)
            {
                var comments = _unitOfWork.Comments.GetCommentsWithPosts().OrderByDescending(c => c.CreateDate);

                if (comments == null)
                    return HttpNotFound();

                return View(comments.ToList());
            }

            IEnumerable<Comment> commentsForPost = null;
            if (pending == false)
                commentsForPost = _unitOfWork.Comments.GetCommentsForPost(postId.Value).OrderByDescending(c => c.CreateDate);
            else
                commentsForPost = _unitOfWork.Comments.GetPendingCommentsForPost(postId.Value).OrderByDescending(c => c.CreateDate);

            if (commentsForPost == null)
                return HttpNotFound();

            return View(commentsForPost.ToList());

        }

        // Returns a list with only approved comments that belong to the specified post
        // In descending order of date of creation
        [AllowAnonymous]
        public ActionResult CommentsForPost(int? postId)
        {
            if (postId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var comments = _unitOfWork.Comments.GetApprovedCommentsForPost(postId.Value);
            if (comments == null)
                return HttpNotFound();

            return PartialView(comments.OrderByDescending(c => c.CreateDate));
        }


         [Authorize(Roles="Admin")]
        // GET: /Comment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Comment comment = _unitOfWork.Comments.GetComment(id.Value);
            if (comment == null)
                return HttpNotFound();
            
            return View(comment);
        }


        /// <summary>
        ///GET: /Comment/Create
        /// Returns a partial view for creating comments if the user is authenticated.
        /// Sets the user's email as the default value for the email associated with the comment.
        /// If the id of the parent comment is not null, sets a message
        /// that displays user name and date for the comment the reply is sent to.
        /// If the user is not authenticated, a partial view is returned for logging in.
        /// </summary>
        /// <param name="parentId">Id if the comment the new comment is a reply to </param>
        /// <param name="postId">The id of the post to be commented</param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Create(int? parentId, int postId, string requestUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = _unitOfWork.Users.GetUser(User.Identity.GetUserId());
                if (user == null)
                    return HttpNotFound();
                Comment comment = new Comment() { Email = user.Email, PostId = postId };
                CommentViewModel viewModel = new CommentViewModel();

                if (parentId != null)
                {
                    Comment parentComment = _unitOfWork.Comments.GetComment(parentId.Value);
                    if (parentComment != null)
                    {
                        viewModel.ResponseToMessage = string.Format("Reply to: {0} {1} ", parentComment.ApplicationUser.UserName, parentComment.CreateDate);
                        comment.ParentCommentId = parentComment.Id;
                    }
                    else { viewModel.ResponseToMessage = ""; }
                }
                viewModel.Comment = comment;
                return PartialView(viewModel);
            }

            ViewBag.RequestUrl = requestUrl ?? Request.RawUrl;
           
            return PartialView("LogIn");
        }


        // POST: /Comment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.ApplicationUserId = User.Identity.GetUserId();
                comment.CreateDate = DateTime.Now;
                if (!_unitOfWork.Posts.PostExists(comment.PostId) 
                    || (comment.ParentCommentId !=null && !_unitOfWork.Comments.CommentExists(comment.ParentCommentId.Value)))
                {
                    return HttpNotFound();
                }
                _unitOfWork.Comments.Add(comment);
                _unitOfWork.Complete();

                ValueProviderResult commentContent = new ValueProviderResult("", "", System.Globalization.CultureInfo.CurrentCulture);
                ModelState.SetModelValue("comment.Content", commentContent);
                var viewModel = new CommentViewModel()
                {
                    Comment = new Comment(),
                    CommentStatusMesssage = "Your comment has been registered and will appear after approval from the admin"
                };
                return PartialView(viewModel);
            }

            var returnViewModel = new CommentViewModel()
            {
                Comment = comment,
                CommentStatusMesssage = "Your comment has not been registered"
            };
            return PartialView(returnViewModel);
        }

        /// <summary>
        /// Changes the approved attribute of the comment: from true to false or from false to true.
        /// </summary>
        /// <param name="id">Comment id</param>
        /// <returns>A partial view with the updated comment.</returns>
        [HttpPost, Authorize(Roles="Admin")]
        public ActionResult Approve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = _unitOfWork.Comments.GetCommentWithPostAndParentComment(id.Value);
            if (comment != null)
            {
                if (comment.Approved == true)
                    comment.Approved = false;
                else
                    comment.Approved = true;

                _unitOfWork.Complete();
            }
            return PartialView(comment);
        }


        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            var comments = _unitOfWork.Comments.GetCommentsWithPosts().OrderByDescending(c => c.CreateDate);
            return PartialView(comments.ToList());
        }

 
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Comment comment = _unitOfWork.Comments.GetComment(id.Value);
            if (comment == null)
                return HttpNotFound();
            
            return View(comment);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<Comment> replies = new List<Comment>();
            CascadeComments(id, replies);

            Comment comment = _unitOfWork.Comments.GetComment(id);
            replies.Add(comment);

            for (int i = 0; i < replies.Count; i++)
            {
                _unitOfWork.Comments.Remove(replies[i]);
            }
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Fills a list with all the replies to a comment.
        /// </summary>
        /// <param name="id">The id of the comment for which the replies are to be collected</param>
        /// <param name="replies">The list with reply comments</param>
        private void CascadeComments(int id, List<Comment> replies)
        {
            Comment comment = _unitOfWork.Comments.GetCommentWithReplies(id);
            foreach (var reply in comment.Replies)
            {
                if (reply.Replies.Count() > 0)
                {
                    CascadeComments(reply.Id, replies);
                }
                replies.Add(reply);
            }
        }

    }
}

Blog/Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using Blog.Repositories;
using Blog.ViewModels;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ResourceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ResourceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var resources = _unitOfWork.Resources.GetResources();
            return View(resources);
        }

        public ActionResult Upload()
        {
            return View();
        }

        // Saves an uploaded file to the database, with its name and content-type.
        // Returns a Json object with the result (success or failure)
        [HttpPost]
        public JsonResult UploadFile(HttpPostedFileBase qqfile)
        {
            HttpPostedFileBase file = Request.Files[0];
            if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName) &&  !string.IsNullOrEmpty(file.ContentType))
            {
                string fileName = file.FileName;
                string fileContentType = file.ContentType;
                byte[] fileBytes = new byte[file.ContentLength];
                file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));

                Resource resource = new Resource()
                {
                    FileName = fileName,
                    ContentType = fileContentType,
                    FileBytes = fileBytes
                };
                _unitOfWork.Resources.Add(resource);
                _unitOfWork.Complete();
                return Json(new { success = true }, "application/json");
            }
            return Json(new { success = false }, "application/json");
        }

        // Returns the specified resource for download
        [AllowAnonymous]
        public ActionResult GetFile(int id)
        {
            var resource = _unitOfWork.Resources.GetResource(id);
            if (resource != null)
            {
                byte[] data;

                if (resource != null)
                {
                    data = (byte[])resource.FileBytes.ToArray();
                    return File(data, resource.ContentType, resource.FileName);
                }

                return File(new byte[0], string.Empty, string.Empty);
            }
            return new HttpNotFoundResult();
        }

        // Lists the resources for a specified, published post
        [AllowAnonymous]
        public ActionResult List(int id)
        {
            Post post = _unitOfWork.Posts.GetPost(id);
            if (post != null && post.Status == PostStatus.published)
            {
                List<Resource> resources = _unitOfWork.Resources.GetResourcesForPost(id).ToList();
                return PartialView(resources);
            }
            return PartialView(new List<Resource>());
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Resource resource = _unitOfWork.Resources.GetResource(id.Value);
            if (resource == null)
                return HttpNotFound();
            
            return View(resource);
        }

        // Edits description for a resource
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Resource resource)
        {
            var res = _unitOfWork.Resources.GetResource(resource.Id);
            if (ModelState.IsValid)
            {
                if (res != null)
                {
                    res.Description = resource.Description;
                    _unitOfWork.Complete();
                    return RedirectToAction("Index");
                }
            }

            return View(res);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Resource resource = _unitOfWork.Resources.GetResource(id.Value);
            if (resource == null)
                return HttpNotFound();
            
            return View(resource);
        }

        // POST: /Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resource resource = _unitOfWork.Resources.GetResource(id);
            _unitOfWork.Resources.Remove(resource);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

        // Returns view for associating resources with posts
        public ActionResult ToPost(int postId)
        {
            var resources = _unitOfWork.Resources.GetResourcesWithPosts();
            var viewModel = new ResourcesToPostViewModel()
            {
                PostId = postId,
                Resources = resources
            };
            return View(viewModel);
        }

        // Associate a post with the resouces that the user has chosen to add.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ToPost()
        {
            int postId = 0;
            if (Request["postId"] != null)
            {
                if (int.TryParse(Request["postId"].ToString(), out postId))
                {
                    var post = _unitOfWork.Posts.GetPost(postId);

                    if (post != null)
                    {
                        if (Request["add"] != null)
                        {
                            List<int> ids = new List<int>();
                            int id = 0;
                            foreach (var selection in Request["add"].Split(','))
                            {
                                if (int.TryParse(selection, out id))
                                {
                                    ids.Add(id);
                                }
                            }
                            var resources = _unitOfWork.Resources.GetResourcesWithIds(ids).ToList();
                            foreach (var item in post.Resources)
                                resources.Add(item);
                            post.Resources = resources.ToList();
                            _unitOfWork.Complete();
                            ViewBag.Message = "Resource has been added to post!";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Error adding post";
                    }
                }
            }

            var resourcesBack = _unitOfWork.Resources.GetResourcesWithPosts();
            var viewModel = new ResourcesToPostViewModel()
            {
                PostId = postId,
                Resources = resourcesBack.ToList()
            };
            return View(viewModel);
        }

        public ActionResult RemoveFromPost(int id, int postId)
        {
            var resource = _unitOfWork.Resources.GetResource(id);
            if (resource == null)
                return HttpNotFound();

            var viewModel = new ResourceOfPostViewModel()
            {
                Resource = resource,
                PostId = postId
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveFromPost()
        {
            if (Request["id"] != null && Request["postId"] != null )
            {
                int id = 0;
                int postId = 0;
                if (int.TryParse(Request["id"].ToString(), out id) && int.TryParse(Request["postId"].ToString(), out postId))
                {

                    var post = _unitOfWork.Posts.GetPost(postId);
                    var resource = _unitOfWork.Resources.GetResource(id);
                    if (post != null)
                    {
                        post.Resources.Remove(resource);
                        _unitOfWork.Complete();
                    }
                    return RedirectToAction("ToPost", new {postId});
                }
            }

             return HttpNotFound();
        }

    }
}

Blog/Views/Post/Create.cshtml
@model Blog.ViewModels.PostViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Create";
}

<h2>New post</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="formdiv">

        @Html.ValidationSummary(true)

        <div>
            @Html.LabelFor(model => model.Post.Titel)

            @Html.EditorFor(model => model.Post.Titel)
            @Html.ValidationMessageFor(model => model.Post.Titel)

        </div>

        <div>
            @Html.LabelFor(model => model.Post.Content)

            @Html.EditorFor(model => model.Post.Content)
            @Html.ValidationMessageFor(model => model.Post.Content)

        </div>

        <div>
            @Html.LabelFor(model => model.Post.Status, new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.Post.Status, Model.PostStatus, "[Please select]")
            @Html.ValidationMessageFor(model => model.Post.Status)
        </div>


        <div class="no-border">

            <input type="submit" name="button" value="Save" class="more" />

        </div>
    </div>
}

<div class="link">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Post/Delete.cshtml
@model Blog.Models.Post

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this post?</h3>
<div>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="no-border">
            <input type="submit" value="Delete" class="more" />
        </div>
    <div class="link">
        @Html.ActionLink("Back to List", "Index")
    </div>
    }</div>

Blog/Views/Post/Details.cshtml
@model Blog.Models.Post

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Post</h4>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.Raw(Model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resources)
        </dt>

        <dd>
            @Model.Resources.Count()
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) | @Html.ActionLink("Back to List", "Index")
</p>

Blog/Views/Post/Edit.cshtml
@model Blog.ViewModels.PostViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Edit";
}


<h2>Edit post</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="formdiv">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Post.Id)

        <div>
            @Html.LabelFor(model => model.Post.Titel)

            @Html.EditorFor(model => model.Post.Titel)
            @Html.ValidationMessageFor(model => model.Post.Titel)

        </div>

        <div>
            @Html.LabelFor(model => model.Post.Content)

            @Html.EditorFor(model => model.Post.Content)
            @Html.ValidationMessageFor(model => model.Post.Content)

        </div>

        <div>
            @Html.LabelFor(model => model.Post.CreateDate)
            @Html.DisplayFor(model => model.Post.CreateDate)
            <input type="hidden" name="createdate" value="@Model.Post.CreateDate" />
        </div>


        <div>
            @Html.LabelFor(model => model.Post.Status)
            @Html.DropDownListFor(model => model.Post.Status, Model.PostStatus, "[Please select]")
            @Html.ValidationMessageFor(model => model.Post.Status)

            @if (Model.Post.PublishDate != null)
            {
                @Html.HiddenFor(model => model.Post.PublishDate)
            }
        </div>

        <div>
            <label>Resources: @Model.Post.Resources.Count() item(s)</label>
            @Html.ActionLink("Manage resources", "ToPost", "Resource", new { postId = Model.Post.Id }, new { @class = "link" })
        </div>

        <div class="no-border">

            <input type="submit" name="button" value="Save" class="more" />

        </div>
    </div>
}

<div class="link">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Post/Index.cshtml
@model IEnumerable<Blog.Models.Post>


@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "My posts";
}

<h2>My posts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            <label>Comments</label>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate)
            @if (item.ModifyDate != null)
            {
                <br />
    <span>
        Last modified: 
        @Html.DisplayFor(modelItem => item.ModifyDate)
    </span>
            }
            @if (item.PublishDate != null)
            {
                <br />
                <span>
                    Published:
                    @Html.DisplayFor(modelItem => item.PublishDate)
                </span>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @item.Comments.Count()
            @if (item.Comments.Where(c => c.Approved == false).Count() > 0)
{
    <span>
        (@Html.ActionLink("Pending:", "Index", "Comment", new { postId = item.Id, pending = true }, new { @class = "link" })
        @item.Comments.Where(c => c.Approved == false).Count())
    </span>
            <br />
            }
            @if (item.Comments.Count() > 0)
            {
                @Html.ActionLink("Go to comments", "Index", "Comment", new { postId = item.Id }, new { @class = "link" })
            }
                     
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>